FROM nginx:alpine

# RUN rm /etc/nginx/conf.d/default.conf
RUN mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bak

# USER root

# Ensure nginx user has permissions to the cache and pid directory
RUN mkdir -p /var/cache/nginx/client_temp && \
    chown -R nginx:nginx /var/cache/nginx && \
    mkdir -p /var/run/nginx && \
    chown -R nginx:nginx /var/run/nginx

# Update, upgrade and install some things
RUN apk update && \
    apk upgrade && \
    apk add --no-cache \
        nano \
        ncdu

# Switch back to nginx user
# USER nginx

# disables any user directive in the Nginx configuration file (bug fix)
# RUN sed -i '/^user/s/^/#/' /etc/nginx/nginx.conf

# Copy a new configuration file from your local to the container
COPY ./nginx/nginx.conf /etc/nginx/conf.d
RUN chown -R nginx:nginx /etc/nginx/conf.d

# Expose port 80 and 443 to the host
EXPOSE 80 443

WORKDIR /etc/nginx/conf.d