FROM alpine:latest

# Update, upgrade and install some things
RUN apk update && \
    apk upgrade && \
    apk add --no-cache \
        nano \
        ncdu

# Clean up
RUN rm -rf /var/cache/apk/*

#COPY --chown=www-data:www-data ./src/ /var/www/html/
COPY ./src/ /var/www/html/
RUN ls -R ./var/www/html/

RUN chmod -R 755 /var/www/html

WORKDIR /var/www/html/

CMD ["/bin/sh"]